
desc "Установка зависимостей, сборка с помощью scan"
lane :build_for_testing do
  cocoapods(
    #clean_install: true,
    podfile: "Podfile"
  )
  run_tests(
    build_for_testing: true
  )
end

desc "Запуск тестов на уже скомпилированном приложении"
lane :run_tests_1 do
  run_tests(
    test_without_building: true
  )

end

desc "Вызов первых двух лейнов"
lane :build_and_test do
  build_for_testing
  run_tests_1
end

desc "Runs all the tests"
   lane :build_for_test_main do
       begin
           build_lane()
       rescue => exception
           on_error(exception)
       end
   end

def build_lane
    build_for_testing
    discord_notifier(
      webhook_url: ENV['DISCORD_WEBHOOK_URL'],
      title: "Finished building",
      description: "Success"
    )
end

def on_error(exception)
  discord_notifier(
      webhook_url: ENV['DISCORD_WEBHOOK_URL'],
      title: "Finished building",
      description: "error"
    )
end
